import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#84b095',
        'inverse-surface': '#2f3131',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#274e3d',
        'tertiary-container': '#1a432e',
        'tertiary-fixed': '#c0edd0',
        'inverse-primary': '#a5d0b9',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f0f1f1',
        'on-secondary-fixed': '#002114',
        'surface-container-high': '#e8e8e8',
        'primary-fixed': '#c1ecd4',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#b1f0ce',
        'surface-bright': '#f9f9f9',
        'surface-tint': '#3f6653',
        'on-primary-fixed': '#002114',
        'surface': '#f9f9f9',
        'secondary': '#2c694e',
        'on-background': '#1a1c1c',
        'surface-dim': '#dadada',
        'on-surface': '#1a1c1c',
        'primary': '#012d1d',
        'on-secondary-container': '#316e52',
        'on-primary-container': '#86af99',
        'primary-fixed-dim': '#a5d0b9',
        'surface-container-highest': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'outline': '#717973',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'surface-container': '#eeeeee',
        'on-error-container': '#93000a',
        'background': '#f9f9f9',
        'secondary-container': '#aeeecb',
        'on-secondary-fixed-variant': '#0e5138',
        'on-tertiary-fixed': '#002112',
        'tertiary-fixed-dim': '#a4d1b4',
        'tertiary': '#002d1a',
        'surface-container-low': '#f3f3f3',
        'primary-container': '#1b4332',
        'on-surface-variant': '#414844',
        'error-container': '#ffdad6',
        'surface-variant': '#e2e2e2',
        'on-tertiary-fixed-variant': '#264f39',
        'outline-variant': '#c1c8c2',
        'secondary-fixed-dim': '#95d4b3',
      },
      fontFamily: {
        headline: ['"Playfair Display"', '"Noto Serif"', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
} satisfies Config;
